### ISSUE TITLE
Would there be a way to run this actions for a particular folders or a list? 

### ISSUE THREAD

**Issue by jpvalery** [maxheld83/pandoc#15]
Hi,

Thanks for building this and making it available. I'm scratching my head and I'm hoping you'll be able to offer some guidance. 

We use pandoc to automatically generate some HTML by converting some .md files and inserting some lines of Liquid in between them (parsed from text files in a subdirectory).
The final output for us is a .html file with the html content and liquid code.

We're currently doing this manually but we're hoping we could automate most of the process. 
I.e. could we have the script running for every folder in a list or just for the folder that got content with the PR?  

Curious to hear your thoughts :) Thanks in advance!

**Comment by maxheld83** [comment]
I'm not 100% sure I understand, but you can generally do everything you can with a single `pandoc ` command.

AFAIK, you can provide *multiple* input files, and have them concatenate in *one* output file.
So you can do something like `pandoc -s input1.md input2.md input3.md -o output.html`. 
For more details, see the [pandoc documentation](https://pandoc.org/MANUAL.html).
You can simply pass these arguments into the action like so:

```
      - uses: maxheld83/pandoc@v2
        with:
          args: "-s input1.md input2.md input3.md -o output.html"
```

Alternatively, if you need more control logic (say, a for loop), you can write it up in some `script.sh`, and then provide that to actions as an [alternative entrypoint](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepswithentrypoint). 
Remember that your script has to be executible.

Please close if this solves the issue for you.

**Comment by jpvalery** [comment]
Thanks for the reply Max. Our commands are already written so that's indeed the control logic I was interested in. I'll look further into that. 

Thanks,
