### ISSUE TITLE
migrate to actions 2.0

### ISSUE THREAD

**Issue by maxheld83** [maxheld83/pandoc#3]
as requested by @jessephus

**Comment by maxheld83** [comment]
done

**Comment by jessephus** [comment]
Wow. Thanks so much for the updates @maxheld83! 🙇

**Comment by maxheld83** [comment]
not quite ready yet apparently ... will send you an email when it's done
The fun bugs always show up *after* a release 😏

**Comment by maxheld83** [comment]
*now* it's done (there was a glitch with the released version)
